[versions]
kotlin = "2.0.20"
junit = "4.13.2"
junitJupiter = "5.8.1"
mockk = "1.13.12"
cucumber = "7.19.0"
codec = "1.15"

[libraries]

plugin-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

codec-common = { group = "commons-codec", name = "commons-codec", version.ref = "codec" }

test-junit = { group = "junit", name = "junit", version.ref = "junit" }
test-junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
test-mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
test-cucumber-java = { group = "io.cucumber", name = "cucumber-java", version.ref = "cucumber" }
test-cucumber-junit = { group = "io.cucumber", name = "cucumber-junit", version.ref = "cucumber" }


[bundles]
plugins-gradle = ["plugin-kotlin"]
test = ["test-junit", "test-junit-jupiter", "test-mockk"]
test-cucumber = ["test-cucumber-java", "test-cucumber-junit"]

[plugins]